-- ========================================================
-- BAZAAR MARKETPLACE - SEED CONFIGURATION
-- Production Marketplace: Real Authenticated Users Only
-- ========================================================
-- To preserve a clean, genuine peer-to-peer marketplace:
-- - No fake or demo seller accounts are seeded.
-- - No placeholder, bot-generated, or mock listings are inserted.
-- All listings originate exclusively from authenticated users who have
-- registered with their verified credentials.
