-- ========================================================
-- BAZAAR MARKETPLACE - PURGE DEMO & FAKE SEED LISTINGS
-- Migration: 003_purge_demo_listings.sql
-- Safely removes all hardcoded, seed, bot, and placeholder data
-- while preserving all real listings from authenticated users.
-- ========================================================

-- 1. Remove all listings belonging to unauthenticated or demo sellers
DELETE FROM public.listings
WHERE seller_id NOT IN (SELECT id FROM auth.users)
   OR seller_id IN (
      '10000000-0000-0000-0000-000000000001',
      '20000000-0000-0000-0000-000000000002',
      '30000000-0000-0000-0000-000000000003',
      '40000000-0000-0000-0000-000000000004',
      '50000000-0000-0000-0000-000000000005',
      '60000000-0000-0000-0000-000000000006',
      '70000000-0000-0000-0000-000000000007',
      '80000000-0000-0000-0000-000000000008',
      '00000000-0000-0000-0000-000000000001',
      '00000000-0000-0000-0000-000000000002',
      '00000000-0000-0000-0000-000000000003',
      '00000000-0000-0000-0000-000000000004',
      '11111111-1111-1111-1111-111111111111',
      '22222222-2222-2222-2222-222222222222',
      '33333333-3333-3333-3333-333333333333',
      '44444444-4444-4444-4444-444444444444'
   )
   OR id IN (
      'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
      'b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e',
      'c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f',
      'd4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a',
      'e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f9a0b',
      'f6a7b8c9-d0e1-2f3a-4b5c-6d7e8f9a0b1c',
      '07a8b9c0-d1e2-3f4a-5b6c-7d8e9f0a1b2c',
      '18b9c0d1-e2f3-4a5b-6c7d-8e9f0a1b2c3d'
   );

-- 2. Remove all orphan/demo profiles that do not map to real auth accounts
DELETE FROM public.profiles
WHERE id NOT IN (SELECT id FROM auth.users)
   OR id IN (
      '10000000-0000-0000-0000-000000000001',
      '20000000-0000-0000-0000-000000000002',
      '30000000-0000-0000-0000-000000000003',
      '40000000-0000-0000-0000-000000000004',
      '50000000-0000-0000-0000-000000000005',
      '60000000-0000-0000-0000-000000000006',
      '70000000-0000-0000-0000-000000000007',
      '80000000-0000-0000-0000-000000000008',
      '00000000-0000-0000-0000-000000000001',
      '00000000-0000-0000-0000-000000000002',
      '00000000-0000-0000-0000-000000000003',
      '00000000-0000-0000-0000-000000000004',
      '11111111-1111-1111-1111-111111111111',
      '22222222-2222-2222-2222-222222222222',
      '33333333-3333-3333-3333-333333333333',
      '44444444-4444-4444-4444-444444444444'
   );

-- 3. Ensure listings status and integrity checks
ALTER TABLE public.listings 
DROP CONSTRAINT IF EXISTS listings_seller_authenticated_check;

-- Ensure foreign key constraint strictly ties listings.seller_id to public.profiles.id
-- which in turn is generated by the auth.users trigger
